site_name: human_me
site_description: "Python package to generate and analyze human ME Models."
theme: readthedocs
repo_url: https://github.com/hmbaghdassarian/human_me

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: numpy
            filters:
              - "!^_"             # hide private members (starting with _)
          rendering:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_signature_annotations: true
            show_if_no_docstring: false
            heading_level: 2
            members_order: source
            group_by_category: true
  - exclude:
      glob:
        - 'human_me/me_solver/tests/*'

markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - PSIM: psim.md
  - Installation: install.md
  - API: api.md