site_name: human_me
site_description: "Python package to generate and analyze human ME Models."

theme: readthedocs
repo_url: https://github.com/hmbaghdassarian/human_me
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
  - exclude:
      glob:
        - 'human_me/me_solver/tests/*'

markdown_extensions:
  # - search
  - def_list
  - attr_list
  - admonition
  # - autorefs
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

nav:
  - "Home": index.md
  - "PSIM": psim.md
  - "Installation": install.md
  - "API": api.md
